version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://appuser:apppassword@db:5432/appdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #volumes:
    #  - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
